export const CATALOGO_INICIAL = [
  { id: 'c1', nombre: 'Aceite girasol', precioRef: 2600 },
  { id: 'c2', nombre: 'Aceite oliva', precioRef: 10600 },
  { id: 'c3', nombre: 'Agua micelar', precioRef: null },
  { id: 'c4', nombre: 'Algodón CHICO', precioRef: 1428 },
  { id: 'c5', nombre: 'Ananá', precioRef: null },
  { id: 'c6', nombre: 'Arroz blanco', precioRef: 2000 },
  { id: 'c7', nombre: 'Atún', precioRef: 2500 },
  { id: 'c8', nombre: 'Avena instantánea fina', precioRef: 2388 },
  { id: 'c9', nombre: 'Azúcar', precioRef: 789 },
  { id: 'c10', nombre: 'Bicarbonato x 50', precioRef: 418 },
  { id: 'c11', nombre: 'Brownie', precioRef: 3000 },
  { id: 'c12', nombre: 'Block hojas rayas Jena', precioRef: 6500 },
  { id: 'c13', nombre: 'Block hojas rayas Joa', precioRef: 4500 },
  { id: 'c14', nombre: 'Bolitas chocolinas', precioRef: 2862 },
  { id: 'c15', nombre: 'Bolsas residuos', precioRef: 1004 },
  { id: 'c16', nombre: 'Cacao en polvo Nesquick', precioRef: 3000 },
  { id: 'c17', nombre: 'Cachafaz', precioRef: null },
  { id: 'c18', nombre: 'Café tostado instantáneo', precioRef: 8652 },
  { id: 'c19', nombre: 'Campari', precioRef: 7990 },
  { id: 'c20', nombre: 'Casamcremç', precioRef: 2600 },
  { id: 'c21', nombre: 'Cepillo barrer', precioRef: 5100 },
  { id: 'c22', nombre: 'Cepillo de dientes', precioRef: null },
  { id: 'c23', nombre: 'Champú Johnson x 400', precioRef: 8260 },
  { id: 'c24', nombre: 'Champú Nutris Garnier Aloe Vera', precioRef: 5400 },
  { id: 'c25', nombre: 'Chimichurri', precioRef: null },
  { id: 'c26', nombre: 'Cif baño', precioRef: 3349 },
  { id: 'c27', nombre: 'Coco rayado', precioRef: 4900 },
  { id: 'c28', nombre: 'Coñac para bizcochuelo', precioRef: 3700 },
  { id: 'c29', nombre: 'Cortina baño', precioRef: null },
  { id: 'c30', nombre: 'Crema de leche', precioRef: 1500 },
  { id: 'c31', nombre: 'Crema depilatoria', precioRef: null },
  { id: 'c32', nombre: 'Cucharitas de té', precioRef: null },
  { id: 'c33', nombre: 'Desodorante corporal antibacterias', precioRef: null },
  { id: 'c34', nombre: 'Desodorante de pie', precioRef: null },
  { id: 'c35', nombre: 'Desodorante piso', precioRef: 3235 },
  { id: 'c36', nombre: 'Destapa cañerías', precioRef: 5326 },
  { id: 'c37', nombre: 'Detergente x 300', precioRef: 2206 },
  { id: 'c38', nombre: 'Dulce de durazno', precioRef: 4250 },
  { id: 'c39', nombre: 'Dulce de leche x kg', precioRef: 6860 },
  { id: 'c40', nombre: 'Dulce de membrillo x kg', precioRef: 3300 },
  { id: 'c41', nombre: 'Durazno natural', precioRef: null },
  { id: 'c42', nombre: 'Escobillón', precioRef: 5202 },
  { id: 'c43', nombre: 'Esponja baño', precioRef: 482 },
  { id: 'c44', nombre: 'Esponja cocina', precioRef: 818 },
  { id: 'c45', nombre: 'Estropajo', precioRef: 542 },
  { id: 'c46', nombre: 'Fideos frescos', precioRef: 2400 },
  { id: 'c47', nombre: 'Fideos moñitos', precioRef: 2322 },
  { id: 'c48', nombre: 'Fideos tallarines', precioRef: 1441 },
  { id: 'c49', nombre: 'Foco', precioRef: 2630 },
  { id: 'c50', nombre: 'Fósforos', precioRef: null },
  { id: 'c51', nombre: 'Fritolín', precioRef: 3500 },
  { id: 'c52', nombre: 'Galletas de agua', precioRef: 999 },
  { id: 'c53', nombre: 'Galletas de arroz', precioRef: 1356 },
  { id: 'c54', nombre: 'Galletas de arroz discos', precioRef: 724 },
  { id: 'c55', nombre: 'Galletas dulces', precioRef: null },
  { id: 'c56', nombre: 'Galletas Firmus x102', precioRef: 2220 },
  { id: 'c57', nombre: 'Galletas Macucas x120', precioRef: 1700 },
  { id: 'c58', nombre: 'Galletas obleas Opera x68', precioRef: 2022 },
  { id: 'c59', nombre: 'Galletas Oreos x110 gr', precioRef: 749 },
  { id: 'c60', nombre: 'Galletas polvoritas x81', precioRef: 520 },
  { id: 'c61', nombre: 'Galletas Rumbas', precioRef: 2296 },
  { id: 'c62', nombre: 'Galletas sonrisas x108', precioRef: 1200 },
  { id: 'c63', nombre: 'Galletas surtidas Desfiles x400', precioRef: 1800 },
  { id: 'c64', nombre: 'Guantes', precioRef: 3072 },
  { id: 'c65', nombre: 'Garbanzos', precioRef: 721 },
  { id: 'c66', nombre: 'Harina leudante', precioRef: 1051 },
  { id: 'c67', nombre: 'Harina leudante integral', precioRef: 1500 },
  { id: 'c68', nombre: 'Hilo dental', precioRef: null },
  { id: 'c69', nombre: 'Hojas dibujo Jena', precioRef: null },
  { id: 'c70', nombre: 'Hojas rayas Jena', precioRef: 5000 },
  { id: 'c71', nombre: 'Jabón líquido lavar ropa', precioRef: 7334 },
  { id: 'c72', nombre: 'Jabón líquido ropa fina', precioRef: null },
  { id: 'c73', nombre: 'Jabón líquido x220', precioRef: 1882 },
  { id: 'c74', nombre: 'Jabón tocador', precioRef: 4093 },
  { id: 'c75', nombre: 'Ketchup', precioRef: 3585 },
  { id: 'c76', nombre: 'Lavandina líquida', precioRef: 1850 },
  { id: 'c77', nombre: 'Lavandina Vim', precioRef: 1825 },
  { id: 'c78', nombre: 'Leche en polvo sin lactosa', precioRef: 1319 },
  { id: 'c79', nombre: 'Leche líquida cero lactosa', precioRef: 1689 },
  { id: 'c80', nombre: 'Lenteja en lata', precioRef: 5350 },
  { id: 'c81', nombre: 'Lentejas cocción rápida', precioRef: 2470 },
  { id: 'c82', nombre: 'Maíz pisingallo', precioRef: 836 },
  { id: 'c83', nombre: 'Maní King', precioRef: 2094 },
  { id: 'c84', nombre: 'Manteca', precioRef: 2009 },
  { id: 'c85', nombre: 'Mayonesa', precioRef: 1260 },
  { id: 'c86', nombre: 'Merienda para compartir', precioRef: 8000 },
  { id: 'c87', nombre: 'Mopa', precioRef: 4142 },
  { id: 'c88', nombre: 'Mostaza', precioRef: 2230 },
  { id: 'c89', nombre: 'MR Músculo naranja', precioRef: 2605 },
  { id: 'c90', nombre: 'Ñoquis', precioRef: 2963 },
  { id: 'c91', nombre: 'Off crema', precioRef: 4076 },
  { id: 'c92', nombre: 'Oxipower limpia baño', precioRef: null },
  { id: 'c93', nombre: 'Orégano', precioRef: null },
  { id: 'c94', nombre: 'Pan de hamburguesas', precioRef: 1606 },
  { id: 'c95', nombre: 'Pan de pancho', precioRef: 1884 },
  { id: 'c96', nombre: 'Pan dulce', precioRef: null },
  { id: 'c97', nombre: 'Pan lactal', precioRef: null },
  { id: 'c98', nombre: 'Pan rallado', precioRef: 1400 },
  { id: 'c99', nombre: 'Pañuelos descartables', precioRef: 2079 },
  { id: 'c100', nombre: 'Papel higiénico Rodrigo', precioRef: 1320 },
  { id: 'c101', nombre: 'Papel higiénico Max 4 x80', precioRef: 4325 },
  { id: 'c102', nombre: 'Pascualina x2', precioRef: 2086 },
  { id: 'c103', nombre: 'Pasta de maní sin azúcar', precioRef: 2850 },
  { id: 'c104', nombre: 'Pasta diente', precioRef: null },
  { id: 'c105', nombre: 'Pastilla para mosquitos', precioRef: 3226 },
  { id: 'c106', nombre: 'Perchas', precioRef: 875 },
  { id: 'c107', nombre: 'Pimentón', precioRef: 700 },
  { id: 'c108', nombre: 'Pimienta blanca', precioRef: 3700 },
  { id: 'c109', nombre: 'Polenta', precioRef: 1400 },
  { id: 'c110', nombre: 'Polvo de hornear', precioRef: 1339 },
  { id: 'c111', nombre: 'Postre chocolate', precioRef: null },
  { id: 'c112', nombre: 'Provenzal', precioRef: null },
  { id: 'c113', nombre: 'Prestobarba mujer', precioRef: null },
  { id: 'c114', nombre: 'Queso port salud', precioRef: 7850 },
  { id: 'c115', nombre: 'Queso barra Ilolay', precioRef: 11000 },
  { id: 'c116', nombre: 'Queso para rayar', precioRef: 11000 },
  { id: 'c117', nombre: 'Queso rayado', precioRef: 1728 },
  { id: 'c118', nombre: 'Quitamanchas', precioRef: 1895 },
  { id: 'c119', nombre: 'Raid', precioRef: null },
  { id: 'c120', nombre: 'Ravioles', precioRef: 3693 },
  { id: 'c121', nombre: 'Rejilla', precioRef: null },
  { id: 'c122', nombre: 'Resma hojas', precioRef: 6198 },
  { id: 'c123', nombre: 'Roicota Light', precioRef: 3350 },
  { id: 'c124', nombre: 'Rollo cocina x200', precioRef: 1580 },
  { id: 'c125', nombre: 'Sal fina', precioRef: null },
  { id: 'c126', nombre: 'Sal gruesa', precioRef: 826 },
  { id: 'c127', nombre: 'Salchichas', precioRef: 1895 },
  { id: 'c128', nombre: 'Salsa tomate', precioRef: 1424 },
  { id: 'c129', nombre: 'Snack sin gluten', precioRef: null },
  { id: 'c130', nombre: 'Suavizante para ropa', precioRef: null },
  { id: 'c131', nombre: 'Té', precioRef: null },
  { id: 'c132', nombre: 'Té verde x25', precioRef: null },
  { id: 'c133', nombre: 'Terma limón', precioRef: 1599 },
  { id: 'c134', nombre: 'Toallas femeninas Always celeste', precioRef: 3200 },
  { id: 'c135', nombre: 'Toallas femeninas diarias', precioRef: 9000 },
  { id: 'c136', nombre: 'Toallitas húmedas', precioRef: 2236 },
  { id: 'c137', nombre: 'Tapas de empanadas', precioRef: 1900 },
  { id: 'c138', nombre: 'Tutucas', precioRef: null },
  { id: 'c139', nombre: 'Vainillín', precioRef: null },
  { id: 'c140', nombre: 'Vinagre de alcohol', precioRef: 2500 },
  { id: 'c141', nombre: 'Vinagre de manzana', precioRef: 1238 },
  { id: 'c142', nombre: 'Vino blanco (mesa)', precioRef: 4590 },
  { id: 'c143', nombre: 'Vino blanco (tomar)', precioRef: 7383 },
  { id: 'c144', nombre: 'Vino comida', precioRef: 1489 },
  { id: 'c145', nombre: 'Vino tinto', precioRef: 5778 },
  { id: 'c146', nombre: 'Yerba La Merced', precioRef: 2600 },
  { id: 'c147', nombre: 'Yerba Taragüi', precioRef: 2400 },
  { id: 'c148', nombre: 'Yerbiado x50', precioRef: null },
  { id: 'c149', nombre: 'Yogurt', precioRef: 500 },
  { id: 'c150', nombre: 'Yogurt bebible', precioRef: 1400 },
  { id: 'c151', nombre: 'Yogurt Dahí', precioRef: 1600 },
  { id: 'c152', nombre: 'Ziploc chicas', precioRef: 2771 },
  { id: 'c153', nombre: 'Masas para empanadas', precioRef: 7860 },
  { id: 'c154', nombre: 'Agua oxigenada', precioRef: null },
  { id: 'c155', nombre: 'Lisoform', precioRef: null },
  { id: 'c156', nombre: 'Bolsas consorcio', precioRef: null },
  { id: 'c157', nombre: 'Proteína de chocolate / Cindor', precioRef: null },
  { id: 'c158', nombre: 'Caldo de verdura', precioRef: null },
]
