export const CATEGORIES = [
  {
    id: 'impuestos',
    label: 'Impuestos',
    color: 'red',
    bg: 'bg-red-100',
    text: 'text-red-700',
    border: 'border-red-200',
    dot: 'bg-red-500',
    card: 'from-red-500 to-red-600',
    icon: '🏛️',
  },
  {
    id: 'club',
    label: 'Club',
    color: 'blue',
    bg: 'bg-blue-100',
    text: 'text-blue-700',
    border: 'border-blue-200',
    dot: 'bg-blue-500',
    card: 'from-blue-500 to-blue-600',
    icon: '⚽',
  },
  {
    id: 'escuela',
    label: 'Escuela',
    color: 'green',
    bg: 'bg-green-100',
    text: 'text-green-700',
    border: 'border-green-200',
    dot: 'bg-green-500',
    card: 'from-green-500 to-green-600',
    icon: '📚',
  },
  {
    id: 'compras',
    label: 'Compras',
    color: 'purple',
    bg: 'bg-purple-100',
    text: 'text-purple-700',
    border: 'border-purple-200',
    dot: 'bg-purple-500',
    card: 'from-purple-500 to-purple-600',
    icon: '🛒',
  },
  {
    id: 'servicios',
    label: 'Servicios',
    color: 'orange',
    bg: 'bg-orange-100',
    text: 'text-orange-700',
    border: 'border-orange-200',
    dot: 'bg-orange-500',
    card: 'from-orange-500 to-orange-600',
    icon: '💡',
  },
  {
    id: 'salud',
    label: 'Salud',
    color: 'pink',
    bg: 'bg-pink-100',
    text: 'text-pink-700',
    border: 'border-pink-200',
    dot: 'bg-pink-500',
    card: 'from-pink-500 to-pink-600',
    icon: '🏥',
  },
  {
    id: 'otros',
    label: 'Otros',
    color: 'gray',
    bg: 'bg-gray-100',
    text: 'text-gray-700',
    border: 'border-gray-200',
    dot: 'bg-gray-500',
    card: 'from-gray-500 to-gray-600',
    icon: '📦',
  },
]

export const getCategoryById = (id) =>
  CATEGORIES.find((c) => c.id === id) ?? CATEGORIES[CATEGORIES.length - 1]
